---
- hosts: vcl
  user: root
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/setup.yml
    - include: tasks/init.yml
    - include: tasks/initdb.yml
    - include: tasks/openstack.yml
  handlers:
    - include: handlers/setup.yml
